// =============================================================================
// Tileset data - GENERATED by tools/tileset_build.py, do not edit by hand
// =============================================================================
// Source: tileset.ctm

#include "tileset_data.h"

// Character bitmaps, eight bytes each.
const unsigned char tileset_charset[TILESET_CHAR_COUNT * 8] = {
    0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,   // char 0
    0xff, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0,   // char 1
    0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,   // char 2
    0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0,   // char 3
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,   // char 4
    0x55, 0x55, 0xff, 0xff, 0xff, 0xff, 0x55, 0x55,   // char 5
    0xff, 0x07, 0x07, 0x57, 0xff, 0xc1, 0xc1, 0xd5,   // char 6
    0x7d, 0x7d, 0x7d, 0x7d, 0x7d, 0x7d, 0x7d, 0x7d,   // char 7
    0x55, 0xff, 0xff, 0xc3, 0xc3, 0xff, 0xff, 0x55,   // char 8
    0xff, 0xf5, 0xd5, 0xd6, 0xda, 0xda, 0xda, 0xda,   // char 9
    0xda, 0xda, 0xda, 0xda, 0xda, 0xda, 0xda, 0xda,   // char 10
    0xff, 0xf5, 0xd5, 0xd6, 0xda, 0xda, 0xda, 0xd5,   // char 11
    0xda, 0xda, 0xda, 0xda, 0xda, 0xda, 0xda, 0xd5,   // char 12
    0xff, 0xe5, 0xe9, 0xe9, 0xe9, 0xe9, 0xe9, 0xe9,   // char 13
    0xe9, 0xe9, 0xe9, 0xe9, 0xe9, 0xe9, 0xe9, 0xe9,   // char 14
    0x54, 0xa5, 0xa9, 0xa9, 0xa9, 0xa9, 0xa9, 0xa9,   // char 15
    0xe9, 0xe9, 0xe9, 0xe9, 0xe9, 0xe9, 0xd9, 0xd5,   // char 16
    0xa9, 0xa9, 0xa9, 0xa9, 0xa9, 0x69, 0x59, 0x55,   // char 17
    0x54, 0xa5, 0xa9, 0xa9, 0xa9, 0xa9, 0x69, 0x55,   // char 18
    0xf0, 0x3c, 0x0f, 0xc3, 0xf0, 0x3c, 0x0f, 0xc3,   // char 19
    0x99, 0xcc, 0xcc, 0x66, 0x66, 0x33, 0x33, 0x99,   // char 20
    0xff, 0xfd, 0xfd, 0xfd, 0xfd, 0xfd, 0xfd, 0xfd,   // char 21
    0xfd, 0xfd, 0xfd, 0xfd, 0xfd, 0xfd, 0xfd, 0xfd,   // char 22
    0xff, 0xd5, 0xff, 0xff, 0xff, 0xff, 0xd5, 0xd5,   // char 23
    0xff, 0x55, 0xff, 0xff, 0xff, 0xff, 0x55, 0x55,   // char 24
    0x55, 0x5d, 0x7d, 0x7d, 0xfd, 0xfd, 0xfd, 0x55,   // char 25
    0x55, 0xfd, 0xfd, 0xfd, 0xfd, 0xfd, 0xfd, 0x55,   // char 26
    0x55, 0xfd, 0xfd, 0xfd, 0x7d, 0x7d, 0x5d, 0x55,   // char 27
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x03,   // char 28
    0xc0, 0xf0, 0xf0, 0x3c, 0x3c, 0x0f, 0x0f, 0x03,   // char 29
    0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x50, 0x40,   // char 30
    0x01, 0x01, 0x05, 0x04, 0x00, 0x00, 0x00, 0x00,   // char 31
    0x40, 0xc0, 0xf0, 0x34, 0x10, 0x00, 0x00, 0x00,   // char 32
};

// Indexed by TILESET_ENTRY(variant, tile); variants run in order.
const unsigned char tileset_cell_char[TILESET_TILE_CELLS][TILESET_ENTRY_COUNT] = {
    { // cell 0 (col 0, row 0)
          0,   1,   5,   7,   8,   8,   8,   8,   0,  13,  13,   7,   5,  21,  23,  21,  23,   7,  28,   // TILE_VARIANT_LIT
          0,   1,   5,   7,   8,   8,   8,   8,   0,  13,  13,   7,   5,  21,  23,  21,  23,   7,  28,   // TILE_VARIANT_FOG
    },
    { // cell 1 (col 1, row 0)
          0,   2,   5,   6,   5,   6,   5,   6,   0,   2,   2,  19,   5,   2,  24,   2,  24,  25,   4,   // TILE_VARIANT_LIT
          0,   2,   5,   6,   5,   6,   5,   6,   0,   2,   2,  19,   5,   2,  24,   2,  24,  25,   4,   // TILE_VARIANT_FOG
    },
    { // cell 2 (col 2, row 0)
          0,   2,   5,   6,   5,   6,   5,   6,   9,   2,   2,  19,   5,   2,  24,   2,  24,  26,   4,   // TILE_VARIANT_LIT
          0,   2,   5,   6,   5,   6,   5,   6,   9,   2,   2,  19,   5,   2,  24,   2,  24,  26,   4,   // TILE_VARIANT_FOG
    },
    { // cell 3 (col 0, row 1)
          0,   3,   6,   7,   7,   7,   6,   6,   0,  14,  14,   7,  20,  22,   3,  22,   3,   7,   4,   // TILE_VARIANT_LIT
          0,   3,   6,   7,   7,   7,   6,   6,   0,  14,  14,   7,  20,  22,   3,  22,   3,   7,   4,   // TILE_VARIANT_FOG
    },
    { // cell 4 (col 1, row 1)
          0,   4,   6,   6,   6,   6,   6,   6,   9,  15,  15,  19,  20,   4,   4,   4,   4,  26,  29,   // TILE_VARIANT_LIT
          0,   4,   6,   6,   6,   6,   6,   6,   9,  15,  15,  19,  20,   4,   4,   4,   4,  26,  29,   // TILE_VARIANT_FOG
    },
    { // cell 5 (col 2, row 1)
          0,   4,   6,   6,   6,   6,   6,   6,  10,   4,   4,  19,  20,   4,   4,   4,   4,  26,  30,   // TILE_VARIANT_LIT
          0,   4,   6,   6,   6,   6,   6,   6,  10,   4,   4,  19,  20,   4,   4,   4,   4,  26,  30,   // TILE_VARIANT_FOG
    },
    { // cell 6 (col 0, row 2)
          0,   3,   6,   7,   7,   7,   6,   6,  11,  16,  16,   7,  20,  22,   3,  22,   3,   7,   4,   // TILE_VARIANT_LIT
          0,   3,   6,   7,   7,   7,   6,   6,  11,  16,  16,   7,  20,  22,   3,  22,   3,   7,   4,   // TILE_VARIANT_FOG
    },
    { // cell 7 (col 1, row 2)
          0,   4,   6,   6,   6,   6,   6,   6,  12,  17,  17,  19,  20,   4,   4,   4,   4,  27,  31,   // TILE_VARIANT_LIT
          0,   4,   6,   6,   6,   6,   6,   6,  12,  17,  17,  19,  20,   4,   4,   4,   4,  27,  31,   // TILE_VARIANT_FOG
    },
    { // cell 8 (col 2, row 2)
          0,   4,   6,   6,   6,   6,   6,   6,  12,  18,  18,  19,  20,   4,   4,   4,   4,  26,  32,   // TILE_VARIANT_LIT
          0,   4,   6,   6,   6,   6,   6,   6,  12,  18,  18,  19,  20,   4,   4,   4,   4,  26,  32,   // TILE_VARIANT_FOG
    },
};

// Indexed by TILESET_ENTRY(variant, tile); variants run in order.
const unsigned char tileset_cell_color[TILESET_TILE_CELLS][TILESET_ENTRY_COUNT] = {
    { // cell 0 (col 0, row 0)
          8,   8,   8,   8,   9,   9,   9,   9,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   9,   // TILE_VARIANT_LIT
          8,   8,   8,   8,   9,   9,   9,   9,   8,   8,   8,   8,   8,   8,   8,   8,   8,   8,   9,   // TILE_VARIANT_FOG
    },
    { // cell 1 (col 1, row 0)
          8,   8,   8,  14,   8,  14,   8,  14,   8,   8,   8,   7,   8,   8,   8,   8,   8,  10,   8,   // TILE_VARIANT_LIT
          8,   8,   8,  14,   8,  14,   8,  14,   8,   8,   8,   7,   8,   8,   8,   8,   8,  10,   8,   // TILE_VARIANT_FOG
    },
    { // cell 2 (col 2, row 0)
          8,   8,   8,  14,   8,  14,   8,  14,   8,   8,   8,   7,   8,   8,   8,   8,   8,  10,   8,   // TILE_VARIANT_LIT
          8,   8,   8,  14,   8,  14,   8,  14,   8,   8,   8,   7,   8,   8,   8,   8,   8,  10,   8,   // TILE_VARIANT_FOG
    },
    { // cell 3 (col 0, row 1)
          8,   8,  14,   8,   8,   8,  14,  14,   8,   8,   8,   8,   7,   8,   8,   8,   8,   8,   8,   // TILE_VARIANT_LIT
          8,   8,  14,   8,   8,   8,  14,  14,   8,   8,   8,   8,   7,   8,   8,   8,   8,   8,   8,   // TILE_VARIANT_FOG
    },
    { // cell 4 (col 1, row 1)
          8,   8,  14,  14,  14,  14,  14,  14,   8,   8,   8,   7,   7,   8,   8,   8,   8,  10,   9,   // TILE_VARIANT_LIT
          8,   8,  14,  14,  14,  14,  14,  14,   8,   8,   8,   7,   7,   8,   8,   8,   8,  10,   9,   // TILE_VARIANT_FOG
    },
    { // cell 5 (col 2, row 1)
          8,   8,  14,  14,  14,  14,  14,  14,   8,   8,   8,   7,   7,   8,   8,   8,   8,  10,   9,   // TILE_VARIANT_LIT
          8,   8,  14,  14,  14,  14,  14,  14,   8,   8,   8,   7,   7,   8,   8,   8,   8,  10,   9,   // TILE_VARIANT_FOG
    },
    { // cell 6 (col 0, row 2)
          8,   8,  14,   8,   8,   8,  14,  14,   8,   8,   8,   8,   7,   8,   8,   8,   8,   8,   8,   // TILE_VARIANT_LIT
          8,   8,  14,   8,   8,   8,  14,  14,   8,   8,   8,   8,   7,   8,   8,   8,   8,   8,   8,   // TILE_VARIANT_FOG
    },
    { // cell 7 (col 1, row 2)
          8,   8,  14,  14,  14,  14,  14,  14,   8,   8,   8,   7,   7,   8,   8,   8,   8,  10,   9,   // TILE_VARIANT_LIT
          8,   8,  14,  14,  14,  14,  14,  14,   8,   8,   8,   7,   7,   8,   8,   8,   8,  10,   9,   // TILE_VARIANT_FOG
    },
    { // cell 8 (col 2, row 2)
          8,   8,  14,  14,  14,  14,  14,  14,   8,   8,   8,   7,   7,   8,   8,   8,   8,  10,  10,   // TILE_VARIANT_LIT
          8,   8,  14,  14,  14,  14,  14,  14,   8,   8,   8,   7,   7,   8,   8,   8,   8,  10,  10,   // TILE_VARIANT_FOG
    },
};
