#ifndef TILESET_DATA_H
#define TILESET_DATA_H

// =============================================================================
// Tileset data - GENERATED by tools/tileset_build.py, do not edit by hand
// =============================================================================
// Source: tileset.ctm
//
// The grid frame and the fog checkerboard are generated overlay layers, not
// hand drawn artwork. Re-run the tool after changing the CTM file.

#define TILESET_CHAR_COUNT   52
#define TILESET_TILE_COUNT   20
#define TILESET_TILE_W       3
#define TILESET_TILE_H       3
#define TILESET_TILE_CELLS   9

#define TILE_VARIANT_LIT       0
#define TILE_VARIANT_FOG       1
#define TILE_VARIANT_COUNT   2

// Global VIC colour registers this tileset was authored against.
#define TILESET_COLOR_BG0    11   // $d021 - also the colour the layers stamp
#define TILESET_COLOR_BG1    12   // $d022
#define TILESET_COLOR_BG2    9   // $d023

extern const unsigned char tileset_charset[TILESET_CHAR_COUNT * 8];
extern const unsigned char tileset_char_color[TILESET_CHAR_COUNT];
extern const unsigned char tileset_tile_chars[TILE_VARIANT_COUNT][TILESET_TILE_COUNT][TILESET_TILE_CELLS];

#endif // TILESET_DATA_H
