#ifndef TILESET_DATA_H
#define TILESET_DATA_H

// =============================================================================
// Tileset data - GENERATED by tools/tileset_build.py, do not edit by hand
// =============================================================================
// Source: tileset.ctm
//
// The grid frame is a generated layer, not hand drawn artwork. The optional
// fog mask is disabled by default. Re-run the tool after changing the CTM.

#define TILESET_CHAR_COUNT   33
#define TILESET_TILE_COUNT   19
#define TILESET_TILE_W       3
#define TILESET_TILE_H       3
#define TILESET_TILE_CELLS   9

#define TILE_VARIANT_LIT       0
#define TILE_VARIANT_FOG       1
#define TILE_VARIANT_COUNT   2

// Global VIC colour registers this tileset was authored against.
#define TILESET_COLOR_BG0    11   // $d021 - also the colour the layers stamp
#define TILESET_COLOR_BG1    12   // $d022
#define TILESET_COLOR_BG2    9   // $d023

extern const unsigned char tileset_charset[TILESET_CHAR_COUNT * 8];

// Combined tile index: variant * TILESET_TILE_COUNT + tile.
#define TILESET_ENTRY(variant, tile)  ((variant) * TILESET_TILE_COUNT + (tile))
#define TILESET_ENTRY_COUNT           (TILE_VARIANT_COUNT * TILESET_TILE_COUNT)

// Cell-major tables: [cell within the tile][combined tile index].
//
// The renderer walks one cell position across many tiles, so keeping the cell
// outermost makes the combined index the array index and every lookup a single
// absolute-indexed load. The variant is folded into that index so fog of war
// costs nothing extra, and the colour is folded in as a parallel table so the
// inner loop never goes through a second lookup to find a character's colour.
extern const unsigned char tileset_cell_char[TILESET_TILE_CELLS][TILESET_ENTRY_COUNT];
extern const unsigned char tileset_cell_color[TILESET_TILE_CELLS][TILESET_ENTRY_COUNT];

#endif // TILESET_DATA_H
